# Generated by Django 4.1.5 on 2023-01-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='ユーザーがこの管理サイトにログインできるかどうかを指定します。', verbose_name='ユーザステータス'),
        ),
    ]
