# Generated by Django 4.1.5 on 2023-01-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_user_living_alone_user_userimage_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='living_alone',
            field=models.CharField(default='年', max_length=128, verbose_name='一人暮らし歴'),
        ),
    ]
