# Generated by Django 4.1.5 on 2023-01-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_user_living_alone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userimage',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/', verbose_name='画像'),
        ),
    ]
