# Generated by Django 4.1.5 on 2023-01-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_user_userimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
    ]
