# Generated by Django 4.1.5 on 2023-01-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_user_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
