# Generated by Django 4.1.5 on 2023-02-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_alter_user_email_alter_user_living_alone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userimage',
            field=models.ImageField(default='', upload_to='images/', verbose_name='プロフィール画像'),
        ),
    ]
