# Generated by Django 4.1.5 on 2023-02-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_user_consecutive_zisui_count_user_zisui_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='consecutive_zisui_count',
            field=models.IntegerField(default='0', verbose_name='総自炊回数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zisui_count',
            field=models.IntegerField(default='0', verbose_name='総自炊回数'),
        ),
    ]
