# Generated by Django 4.1.5 on 2023-03-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_alter_user_consecutive_zisui_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='consecutive_zisui_count',
            field=models.IntegerField(default=0, verbose_name='総自炊回数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zisui_count',
            field=models.IntegerField(default=0, verbose_name='総自炊回数'),
        ),
    ]
