# Generated by Django 4.1.5 on 2023-03-15 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_user_recent_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recent_created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 9, 40, 12, 248151, tzinfo=datetime.timezone.utc), editable=False, verbose_name='最後の投稿日'),
        ),
    ]
