# Generated by Django 4.1.5 on 2023-04-03 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_alter_user_recent_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recent_created_at',
            field=models.DateTimeField(default=datetime.date(2023, 4, 3), verbose_name='最後の投稿日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userimage',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/', verbose_name='プロフィール画像'),
        ),
    ]
