# Generated by Django 4.1.5 on 2023-04-18 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0035_alter_user_recent_created_at_alter_user_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recent_created_at',
            field=models.DateTimeField(default=datetime.date(2023, 4, 18), verbose_name='最後の投稿日'),
        ),
    ]
