# Generated by Django 4.1.5 on 2023-04-18 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0036_alter_user_recent_created_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
