# Generated by Django 4.1.5 on 2023-09-06 14:43

import datetime
from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0037_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', login.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='recent_created_at',
            field=models.DateTimeField(default=datetime.date(2023, 9, 6), verbose_name='最後の投稿日'),
        ),
    ]
