# Generated by Django 4.1.5 on 2023-01-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recippost',
            name='freetext',
            field=models.TextField(default='説明を入力', verbose_name='説明'),
        ),
    ]
