# Generated by Django 4.1.5 on 2023-01-19 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_recippost_freetext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recippost',
            old_name='text',
            new_name='titel',
        ),
    ]
