# Generated by Django 4.1.5 on 2023-01-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_recippost_zisuipost'),
    ]

    operations = [
        migrations.AddField(
            model_name='zisuipost',
            name='author',
            field=models.CharField(default='匿名', max_length=128, verbose_name='投稿者'),
        ),
        migrations.AddField(
            model_name='zisuipost',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='費用'),
        ),
        migrations.AddField(
            model_name='zisuipost',
            name='howtocook',
            field=models.TextField(default='説明を入力', verbose_name='作り方'),
        ),
        migrations.AddField(
            model_name='zisuipost',
            name='ingredients',
            field=models.CharField(default='材料を入力', max_length=128, verbose_name='材料'),
        ),
    ]
