# Generated by Django 4.1.5 on 2023-01-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_zisuipost_author_zisuipost_cost_zisuipost_howtocook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zisuipost',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
