# Generated by Django 4.1.5 on 2023-01-22 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_titel_zisuipost_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zisuipost',
            name='image',
        ),
    ]
