# Generated by Django 4.1.5 on 2023-01-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_zisuipost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='zisuipost',
            name='image',
            field=models.ImageField(default='', upload_to='images/', verbose_name='画像'),
        ),
    ]
