# Generated by Django 4.1.5 on 2023-01-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_zisuipost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zisuipost',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/', verbose_name='画像'),
        ),
    ]
