# Generated by Django 4.1.5 on 2023-01-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_zisuipost_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zisuipost',
            name='cost',
            field=models.CharField(choices=[('費用を選択してください', '費用を選択してください'), ('0~100円', '0~100円'), ('100~200円', '100~200円'), ('200~300円', '200~300円'), ('300~400円', '300~400円'), ('500~600円', '500~600円'), ('600~700円', '600~700円'), ('700~800円', '700~800円'), ('800~900円', '800~900円'), ('900~1000円', '900~1000円'), ('1000円以上', '1000円以上'), ('不明', '不明')], default='費用を選択してください', max_length=20, verbose_name='費用'),
        ),
        migrations.AlterField(
            model_name='zisuipost',
            name='ingredients',
            field=models.TextField(default='材料を入力\n                                    1:\n                                    2:\n                                    3:\n                                    4:\n                                    5:\n                                    6:\n                                    \n                                    \n                                            ', max_length=128, verbose_name='材料'),
        ),
    ]
