# Generated by Django 4.1.5 on 2023-01-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_zisuipost_freetext_alter_zisuipost_howtocook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zisuipost',
            name='freetext',
            field=models.TextField(blank=True, default='コメントを入力', null=True, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='zisuipost',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
    ]
