# Generated by Django 4.1.5 on 2023-02-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_zisuipost_author_alter_zisuipost_howtocook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zisuipost',
            name='author',
            field=models.CharField(default='', max_length=123, verbose_name='投稿者'),
        ),
    ]
