# Generated by Django 4.1.5 on 2023-02-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_zisuipost_cost_alter_zisuipost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='zisuipost',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
