# Generated by Django 4.1.5 on 2023-02-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_zisuipost_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='zisuipost',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
