# Generated by Django 4.1.5 on 2023-03-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_zisuipost_freetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zisuipost',
            name='image',
            field=models.ImageField(default='media/images/1087_01.jpg', upload_to='images/', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='zisuipost',
            name='title',
            field=models.CharField(max_length=100, verbose_name='料理名'),
        ),
    ]
