# Generated by Django 4.1.5 on 2023-03-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_zisuipost_image_alter_zisuipost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zisuipost',
            name='image',
            field=models.ImageField(default='images/1087_01.jpg', upload_to='images/', verbose_name='画像'),
        ),
    ]
