# Generated by Django 4.1.5 on 2023-03-16 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_alter_zisuipost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zisuipost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 20, 33, 21, 430773), editable=False, verbose_name='作成日'),
        ),
    ]
