# Generated by Django 4.1.5 on 2023-03-24 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_alter_zisuipost_created_alter_zisuipost_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zisuipost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 18, 19, 22, 921741), verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='zisuipost',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 24, 18, 19, 22, 921752), null=True, verbose_name='更新日'),
        ),
    ]
