# Generated by Django 4.1.5 on 2023-03-24 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_alter_zisuipost_created_alter_zisuipost_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zisuipost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 9, 31, 54, 913353, tzinfo=datetime.timezone.utc), verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='zisuipost',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 24, 9, 31, 54, 913499, tzinfo=datetime.timezone.utc), null=True, verbose_name='更新日'),
        ),
    ]
