# Generated by Django 4.1.5 on 2023-03-24 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_alter_zisuipost_created_alter_zisuipost_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zisuipost',
            name='updated',
        ),
        migrations.AlterField(
            model_name='zisuipost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 14, 16, 31, 694425, tzinfo=datetime.timezone.utc), verbose_name='作成日'),
        ),
    ]
