# Generated by Django 4.1.5 on 2023-04-18 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_alter_zisuipost_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zisuipost',
            name='created',
            field=models.DateField(default=datetime.date(2023, 4, 18), verbose_name='作成日'),
        ),
    ]
