# Generated by Django 4.1.5 on 2023-09-06 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_alter_zisuipost_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zisuipost',
            name='created',
            field=models.DateField(default=datetime.date(2023, 9, 6), verbose_name='作成日'),
        ),
    ]
